# Site settings
title: Jiajie Zhuo 
email: jiajie_zhuo@163.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: Better to run than curse the road

gems: [jekyll-paginate]

paginate: 5
paginate_path: "blog/page:num"

#pagin
paginate: 5
# Social icons
facebook: JiajieZhuo
linkedin: JiajieZhuo
github: 0lddriv3r
deviantart: username
codepen: username

footer: Â© JiajieZhuo


# Build settings
markdown: kramdown
